### ISSUE TITLE
SlotsSlotsSlots Conflict with Ordinator - Perks of Skyrim SSE

### ISSUE THREAD

**Issue by FoxTailKitsune** [Synthesis-Collective/SlotsSlotsSlots#28]
Compiling
(C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Git\rno5ytvx.h2r\Runner\SlotsSlotsSlots): dotnet build --runtime win-x64 "SlotsSlotsSlots.csproj" -c Release
No extra data to consider.
Compiled
Sha 3b349caaf510d82efcc3091da6ea94a13d54ab90
(): dotnet run --project "C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Git\rno5ytvx.h2r\Runner\SlotsSlotsSlots\SlotsSlotsSlots.csproj" -c Release --runtime win-x64 --no-build check-runnability --DataFolderPath "C:\Program Files\Steam\steamapps\common\Skyrim Special Edition\Data" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Workspace\Plugins.txt
Running
(): dotnet run --project "C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Git\rno5ytvx.h2r\Runner\SlotsSlotsSlots\SlotsSlotsSlots.csproj" --runtime win-x64 --no-build -c Release run-patcher --DataFolderPath "C:\Program Files\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Users\joele\OneDrive\Documents\SSE Apps\Synthesis\Data\SlotsSlotsSlots" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Workspace\Plugins.txt --OutputPath "C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Workspace\0 - SlotsSlotsSlots" --PatcherName SlotsSlotsSlots --PersistencePath C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Persistence
Mutagen version: 0.30.6
Mutagen sha: e1619008d45fb87da7b6a58acfd90553e319545c
Synthesis version: 0.19.2
Synthesis sha: cdf4551d49c580ac024e64e653204e3c20fb6e96
run-patcher --DataFolderPath "C:\Program Files\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Users\joele\OneDrive\Documents\SSE Apps\Synthesis\Data\SlotsSlotsSlots" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Workspace\Plugins.txt --OutputPath "C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Workspace\0 - SlotsSlotsSlots" --PatcherName SlotsSlotsSlots --PersistencePath C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Persistence
Prepping state.
Using TextFileSharedFormKeyAllocator allocator
Reading settings: C:\Users\joele\OneDrive\Documents\SSE Apps\Synthesis\Data\SlotsSlotsSlots\settings.json
System.NullReferenceException: Object reference not set to an instance of an object.
   at SlotsSlotsSlots.Program.MagicEffects(IPatcherState`2 state) in C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Git\rno5ytvx.h2r\Runner\SlotsSlotsSlots\Program.cs:line 378
   at SlotsSlotsSlots.Program.RunPatch(IPatcherState`2 state) in C:\Users\joele\AppData\Local\Temp\Synthesis\ho1omarf.f10\Git\rno5ytvx.h2r\Runner\SlotsSlotsSlots\Program.cs:line 64
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 455
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 403
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 377
Skyrim.MagicEffect WB_A050_SpellTwine_EffectProc_5 08763E:Apocalypse - Magic of Skyrim.esp is altering Carry Weight, and its description was changed to:
"Carry weight increased by <mag> for <dur> seconds."

Skyrim.MagicEffect ORD_Alc_Witchmaster_Effect_Proc_FortifyCarryWeight 0530CA:Ordinator - Perks of Skyrim.esp is altering Carry Weight, and its description was changed to:
"Your use of beneficial alchemy increases your carrying capacity by <mag> for <dur> seconds."

Skyrim.MagicEffect ORD_Alt_WellocsDormantArcana_Effect_Ab_16 0B9EFC:Ordinator - Perks of Skyrim.esp is altering Carry Weight, and its description was changed to:
"Increases number of slots by <mag> slots."

Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

Ordinator seems to be conflicting with SlotsSlotsSlots due to altering "Carry Weight"

I'm not sure what other information to supply.

**Comment by EzioTheDeadPoet** [comment]
Well Ordinator has some issues, with the code that adjusts carryweight effects and their descriptions. 
No clue what exactly cause the mods I tested with are working with no issue. Ordinator might be using a different way to define values for the effect descriptions or something similar which breaks the patcher.

Since I am currently busy with a lot of other stuff I am not feeling like debugging this for Ordinator, especially since I am not using it, but from a proportions perspective I might be able to create an alternative patcher that just makes the same stuff weightless, without altering vanilla weight proportions.(Again not sure when I will do that but thats the only way I currently have an interest in "fixing" this.)

**Comment by EzioTheDeadPoet** [comment]
https://github.com/EzioTheDeadPoet/Weightless-Misc-Items
I made the alternative. The downside is that it is closer to vanilla balancing (armor strength/weight not how much you can carry) (for some it might be an upside) and that it looses the "neatness" aspect of dealing with smaller numbers in the UI.
