### ISSUE TITLE
Error with Wet and Cold

### ISSUE THREAD

**Issue by Roidtakor** [Synthesis-Collective/SlotsSlotsSlots#30]
`Compiling
No extra data to consider
("C:\Users\Test\AppData\Local\Temp\Synthesis\lduz4zvt.ccc\Git\t5tv3krb.hbf\Runner\SlotsSlotsSlots"): "dotnet" "build \"SlotsSlotsSlots.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "e344e2e26eefeec222f396b24972b4c849214e3c"
Running
(""): "dotnet" "run --project \"C:\Users\Test\AppData\Local\Temp\Synthesis\lduz4zvt.ccc\Git\t5tv3krb.hbf\Runner\SlotsSlotsSlots\SlotsSlotsSlots.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"D:\Skyrim SE Modding\Synthesis\Data\Skyrim Special Edition\SlotsSlotsSlots\" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\Test\AppData\Local\Temp\Synthesis\lduz4zvt.ccc\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\Test\AppData\Local\Temp\Synthesis\lduz4zvt.ccc\Workspace\Synthesis\1 - SlotsSlotsSlots\Synthesis.esp\" --PatcherName SlotsSlotsSlots"
Mutagen version: 0.30.4
Mutagen sha: 6066289a117cf735071ff7edb7ef79f58b9c8f2d
Synthesis version: 0.19.2
Synthesis sha: cdf4551d49c580ac024e64e653204e3c20fb6e96
run-patcher --DataFolderPath "D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "D:\Skyrim SE Modding\Synthesis\Data\Skyrim Special Edition\SlotsSlotsSlots" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Test\AppData\Local\Temp\Synthesis\lduz4zvt.ccc\Workspace\Synthesis\Plugins.txt --OutputPath "C:\Users\Test\AppData\Local\Temp\Synthesis\lduz4zvt.ccc\Workspace\Synthesis\1 - SlotsSlotsSlots\Synthesis.esp" --PatcherName SlotsSlotsSlots
Prepping state.
Reading settings: D:\Skyrim SE Modding\Synthesis\Data\Skyrim Special Edition\SlotsSlotsSlots\settings.json
Skyrim.MagicEffect _DRSEnchBackpackBagSpace 000800:_Fuse00_Backpack.esp is altering Carry Weight, and its description was changed to:
"Backpack increases carrying capacity by <mag> slots."

Skyrim.MagicEffect _WetEnchFortifyCarryConstantSelf 0A469A:WetandCold.esp is altering Carry Weight, and its description was changed to:
"Carrying capacity increased by <mag> slots."

System.NullReferenceException: Object reference not set to an instance of an object.
   at SlotsSlotsSlots.Program.MagicEffects(IPatcherState`2 state) in C:\Users\Test\AppData\Local\Temp\Synthesis\lduz4zvt.ccc\Git\t5tv3krb.hbf\Runner\SlotsSlotsSlots\Program.cs:line 369
   at SlotsSlotsSlots.Program.RunPatch(IPatcherState`2 state) in C:\Users\Test\AppData\Local\Temp\Synthesis\lduz4zvt.ccc\Git\t5tv3krb.hbf\Runner\SlotsSlotsSlots\Program.cs:line 55
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 455
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 403
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 377
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 52
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 52
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 65
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 49
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200`

**Comment by Noggog** [comment]
Pushed up some adjustments.  Update the patcher to the latest `main` and try again

**Comment by Roidtakor** [comment]
Dude it worked. Thanks!
